server:
  port: 8085

spring:
  application:
    name: logistic-payment-service
  datasource:
    url: jdbc:postgresql://postgres-payment-service:5432/payment-service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://logistic-eureka:8761/eureka/